### PR TITLE
Added local etcd and local docker stack

### PR DESCRIPTION
**Pull request by sptrakesh**
Work in progress in setting up local environment.  Will add similar for core infrastructure for `dev` next.

### CODE REVIEW

**Comment by drstarson** [comment]
@sptrakesh Thx! I shared a quick question in Slack regarding Docker. Also adding @kells1986 @brandonparis @Loenike to make sure we are all staying in sync.

**Comment by sptrakesh** [comment]
> @sptrakesh Thx! I shared a quick question in Slack regarding Docker. It looks like you're taking essentially the same deployment approach as you did in the other repo. This is good. I just would like to better understand everything that is happening.

@drstarson I replied to your initial question regarding docker on the data model repository.  Yes, we will use Docker as the standard model for packing anything that gets deployed - services, functions, scripts, ...

Docker is probably the most widely supported model at present, and the same image can be deployed to a variety of environments (and cloud platforms) with (usually) no change.

**Comment by brandonparis** [comment]
Pulled and ran locally as per the instructions, looks like everything works (`postgresql` container created and all). @sptrakesh Are you planning a separate PR to seed the data?

**Comment by sptrakesh** [comment]
Yes, @Loenike will be adding those.

**Comment by Loenike** [comment]
@sptrakesh I am creating a INSERT script for adding some minimal data in the database, will push to the repo as well. The corresponding image files are already in the buckets.

**Pull request merged**
